kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
apiVersion: v1
data:
  external-plugins.yaml: |
    Items: null
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - jenkins-x/dummy
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - cb-kubecd/environment-jstrachan-ad2-staging
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - cb-kubecd/environment-jstrachan-ad2-production
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - jstrachan/nodey117
      require_self_approval: true
    blunderbuss: {}
    cat: {}
    cherry_pick_unapproved: {}
    config_updater: {}
    external_plugins:
      cb-kubecd/environment-jstrachan-ad2-staging: null
      jstrachan/nodey117: null
    heart: {}
    owners: {}
    plugins:
      cb-kubecd/environment-jstrachan-ad2-staging:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - size
      - trigger
      - wip
      - heart
      - cat
      - override
      jstrachan/nodey117:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - size
      - trigger
      - wip
      - heart
      - cat
      - override
    requiresig: {}
    sigmention: {}
    slack: {}
    triggers:
    - repos:
      - cb-kubecd/environment-jstrachan-ad2-staging
      trusted_org: cb-kubecd
    - repos:
      - jstrachan/nodey117
      trusted_org: jstrachan
    welcome:
    - message_template: Welcome
