dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.38
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.620
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3877
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.4
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.0
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.16
- name: jx-app-sso
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.10
- name: jx-app-ui
  repository: https://chartmuseum.jx.charts-demo.cloudbees.com
  version: 0.0.696
- name: jx-app-replicator
  repository: http://chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jx-app-prometheus
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3
- name: cb-app-sor
  repository: https://chartmuseum.jx.charts-demo.cloudbees.com
  version: 0.0.2
